"""created schema

Revision ID: 0b6f951c4b07
Revises: 0c64c0a8b718
Create Date: 2021-06-25 15:53:49.461360

"""

# revision identifiers, used by Alembic.
revision = "0b6f951c4b07"
down_revision = "0c64c0a8b718"

import sqlalchemy as sa  # noqa: E402
from alembic import op  # noqa: E402


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "students",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["humans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "homework_results",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("author_id", sa.INTEGER(), nullable=False),
        sa.Column("task_id", sa.INTEGER(), nullable=False),
        sa.Column("solution", sa.VARCHAR(length=120), nullable=True),
        sa.Column("created", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["students.id"],
        ),
        sa.ForeignKeyConstraint(
            ["task_id"],
            ["homeworks.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "teachers",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["humans.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "humans",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=60), nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=60), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "homeworks",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("text", sa.VARCHAR(length=120), nullable=False),
        sa.Column("deadline", sa.DATETIME(), nullable=False),
        sa.Column("teacher_id", sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ["teacher_id"],
            ["teachers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("homeworks")
    op.drop_table("humans")
    op.drop_table("teachers")
    op.drop_table("homework_results")
    op.drop_table("students")
    # ### end Alembic commands ###
