# This is a basic workflow to help you get started with Actions

name: CI

on: 
  push

jobs:
  run_tests:
    runs-on: ubuntu-latest
    container: python:3.8
    name: Run tests

    steps:
      - name: Checkuot code
        uses: actions/checkout@v2

      - name: Run tests with pytest
        run: |
          pip install -r requirements.txt
          pytest tests
